### ISSUE TITLE
Add Psharpen

### ISSUE THREAD

**Issue by Paviluf** [darealshinji/vapoursynth-plugins#1]
Hello,

Can you add the Psharpen script (here and in the ubuntu ppa) please:

https://gist.github.com/4re/2545a281e3f17ba6ef82

Thank you

**Comment by darealshinji** [comment]
I've added Psharpen: https://github.com/darealshinji/vapoursynth-plugins/blob/master/scripts/psharpen.py

I will update the PPA either today or tomorrow.

**Comment by Paviluf** [comment]
Thank you
