### ISSUE TITLE
Update havsfunc.py

### ISSUE THREAD

**Issue by Paviluf** [darealshinji/vapoursynth-plugins#2]
Hello,

I have a problem with havsfunc.py and it will be great if you can update it on the ubuntu ppa to see if it's an old bug or if I need to report it.

Thank you

**Comment by darealshinji** [comment]
HAvsFunc and a few other scripts and plugins were updated.
A new package is now available through the PPA.

**Comment by Paviluf** [comment]
Thank you ;)
