### ISSUE TITLE
mvtools.so plugin being built without -lmvtools

### ISSUE THREAD

**Issue by fmoo** [darealshinji/vapoursynth-plugins#3]
Noticed vapoursynth is no longer able to load the mv library.  Running core.std.LoadLibrary(...) directly emitted the following error:

```
vapoursynth.Error: Failed to load /usr/lib/x86_64-linux-gnu/vapoursynth/mvtools.so. Error given: /usr/lib/x86_64-linux-gnu/vapoursynth/mvtools.so: undefined symbol: mvtools_overlaps_2x4_uint32_t_uint16_t_c
```

Ran an ldconfig -v against the mvtools.so generated by this project and saw it was not dynamically linking against libmvtools.so.  objdump -t showed the necessary symbols not being statically linked either.

I hacked the mvtools Makefile with the following patch and everything seems to be linking up okay:
```diff
diff --git a/plugins/mvtools/Makefile b/plugins/mvtools/Makefile
index 98e951e..8c94907 100644
--- a/plugins/mvtools/Makefile
+++ b/plugins/mvtools/Makefile
@@ -4,7 +4,7 @@ ifeq ($(HAVE_YASM),yes)
 ifeq ($(HAVE_FFTW3F),yes)
 
 LIBNAME = mvtools
-LIBADD = -lfftw3f
+LIBADD = -lfftw3f -lmvtools
 
 VSASFLAGS = -Dprivate_prefix=mvtools -DHIGH_BIT_DEPTH=0 -DBIT_DEPTH=8 -f elf
 ifeq ($(HAVE_X86_64),yes)
```

That said, considering the recent major changes to the build stuff, this is probably not the right fix.

**Comment by darealshinji** [comment]
Thanks for reporting this. It looks like I didn't pay enough attention and didn't realize there's C **and** C++ source files that need to be build. Commit https://github.com/darealshinji/vapoursynth-plugins/commit/022fd21e8ebb2e140cca114facf921b26c4c08a4 should have fixed that.

**Comment by fmoo** [comment]
I can confirm this fixes the issue by statically linking the symbols into mvtools.so.  Thanks for the quick fix!

For what it's worth, I had gotten the affected plugins for xenial from https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth so if this isn't built nightly, you might want to get this explicitly republished.

Feel free to close this out.

**Comment by darealshinji** [comment]
Yeah, I will update the PPA ASAP.
