### ISSUE TITLE
'vs-' prefix to plugin names breaks import on Ubuntu 16.04

### ISSUE THREAD

**Issue by chriskretler** [darealshinji/vapoursynth-plugins#5]
As mentioned here:

https://forum.doom9.org/showthread.php?p=1805103

The hyphen in plugin names in this directory:

/usr/lib/python3/dist-packages/

Does not allow the plugin to be successfully imported.  Sample error:

Python exception: invalid syntax (1.vpy, line 4)
Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 1711, in vapoursynth.vpy_evaluateScript (src/cython/vapoursynth.c:34977)
  File "1.vpy", line 4
    import vs-adjust
                    ^
SyntaxError: invalid syntax

The modules should either be renamed to vs_{plugin_name} or the vs-  removed for the import to be successful.

**Comment by darealshinji** [comment]
Already fixed in https://github.com/darealshinji/vapoursynth-plugins/commit/7ce51c7348f7fc5dbd78a517a135b79fa4460e82
I will update the PPA.
