### ISSUE TITLE
updating vapoursynth packages results in 'Failed to initialize VapourSynth environment' 

### ISSUE THREAD

**Issue by chriskretler** [darealshinji/vapoursynth-plugins#7]
Ubuntu 16.04.

Recent passive package upgrade resulted in vapoursynth r40 being pulled down.  Now, both vsedit and vspipe produce the same result:

$ vspipe --version
Failed to initialize VapourSynth environment

**Comment by darealshinji** [comment]
So it did work with the previous version? I wonder what has changed and what I can do to fix it.

**Comment by chriskretler** [comment]
This comment is more to do with the PPAs for vapoursynth and the plugins than just the plugin source itself.  My apologies if the comment is misplaced.

**Comment by chriskretler** [comment]
Yes, it worked with the previous version of vapoursynth (r38?) though I needed to include the following soft link to get vsedit working:

$ sudo ln -s /usr/lib/x86_64-linux-gnu/libvapoursynth-script.so.0.0.0 /usr/lib/x86_64-linux-gnu/libvapoursynth-script.so

Did the path to vapoursynth.so change in this version of the ppa install?

**Comment by darealshinji** [comment]
Paths are `/usr/lib/x86_64-linux-gnu/libvapoursynth.so` and `/usr/lib/x86_64-linux-gnu/libvapoursynth-script.so.0.0.0`. Nothing has changed as far as I can see.

**Comment by chriskretler** [comment]
Agreed. I just wiped out packages, installed from source and got the same issue.  I'll close this issue and open one in the vapoursynth repo.

I apologize for the misdirection.
